### ISSUE TITLE
Fix "Rubocop/Lint/StringConversionInInterpolation" issue in lib/loba.rb

### ISSUE THREAD

**Issue by rdnewman** [rdnewman/loba#19]
Redundant use of `Object#to_s` in interpolation.

https://codeclimate.com/github/rdnewman/loba/lib/loba.rb#issue_5689b01133dc3f00010638c7

**Comment by yakschuss** [comment]
I noticed that this issue was fixed on `ready_prod`, but not on `master` -- is there a reason for that?

**Comment by rdnewman** [comment]
I probably was working to finish testing or perhaps including other features I wanted for that milestone.
